# -*- coding: utf-8 -*-
"""instagram_osn_analysis_full(both pca and t-SNE).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8CnSRtBElyoe4ubwzHaeC_1BSzez7t9

# Instagram Online Social Networks (OSN) Analysis

**Domain**: Instagram

**Languages**: English, Hindi, Telugu, Marathi, Punjabi, Assamese, Kannada, Tamil, Bengali, Malayalam

### Objectives:
1. Extract Data to JSON (Users, Content, Interactions, Network, Engagement)
2. Load and analyze 5 records
3. Text Preprocessing
4. Vectorization (Indic BERT)
5. Evolutionary Metrics (BLEU, METEOR, WER, CER) & Model Characteristics
6. Stage-wise Visualizations (Network graphs, Engagement matrix plots)

## 1. Environment Setup
"""

!pip install transformers accelerate sacremoses datasets evaluate jiwer nltk networkx matplotlib seaborn plotly scikit-learn nbformat

import nltk
nltk.download('wordnet')
nltk.download('punkt')
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

nltk.download('punkt_tab')

"""## 2. Data Extraction & JSON Creation
We simulate extracting records from Instagram API across 10 regional languages and save them in a JSON format. This represents a large-scale data collection (e.g., 5 Lakhs samples).
"""

import json
import random
import pandas as pd
from datetime import datetime, timedelta

languages = ['English', 'Hindi', 'Telugu', 'Marathi', 'Punjabi',
             'Assamese', 'Kannada', 'Tamil', 'Bengali', 'Malayalam']
sample_texts = {
    'English': 'This is an amazing post on social media! check it out @friend https://link.com #insta',
    'Hindi': 'यह सोशल मीडिया पर एक अद्भुत पोस्ट है! इसे देखें @दोस्त https://link.com #इंस्टा',
    'Telugu': 'ఇది సోషల్ మీడియాలో అద్భుతమైన పోస్ట్! ఇక్కడ చూడండి @మిత్రుడు https://link.com #ఇన్స్టా',
    'Marathi': 'हे सोशल मीडियावर एक आश्चर्यकारक पोस्ट आहे! नक्की बघा @मित्र https://link.com #इंस्टा',
    'Tamil': 'இது சமூக ஊடகங்களில் ஒரு அற்புதமான பதிவு! பார்க்கவும் @நண்பர் https://link.com #இன்ஸ்டா',
    'Bengali': 'এটি সোশ্যাল মিডিয়ায় একটি চমৎকার পোস্ট! দেখুন @বন্ধু https://link.com #ইন্সটা',
    'Malayalam': 'ഇത് സോഷ്യൽ മീഡിയയിലെ ഒരു മികച്ച പോസ്റ്റാണ്! കാണുക @സുഹൃത്ത് https://link.com #ഇൻസ്റ്റ',
    'Kannada': 'ಇದು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ಅದ್ಭುತವಾದ ಪೋಸ್ಟ್ ಆಗಿದೆ! ನೋಡಿ @ಸ್ನೇಹಿತ https://link.com #ಇನ್ಸ್ಟಾ',
    'Punjabi': 'ਇਹ ਸੋਸ਼ਲ ਮੀਡੀਆ ਤੇ ਇੱਕ ਸ਼ਾਨਦਾਰ ਪੋਸਟ ਹੈ! ਦੇਖੋ @ਦੋਸਤ https://link.com ''#ਇੰਸਟਾ',
    'Assamese': 'এইটো ছ’চিয়েল মিডিয়াত এক আচৰিত পোষ্ট! চাওক @বন্ধু https://link.com #ইনষ্টা'
}

def generate_osn_data(num_samples=500000):
    data = []
    for i in range(num_samples):
        lang = random.choice(languages)
        record = {
            'user_profile': {
                'user_id': f'UID_{random.randint(100000, 999999)}',
                'user_name': f'user_{lang.lower()}_{i}',
                'account_creation': (datetime.now() - timedelta(days=random.randint(100, 2500))).strftime('%Y-%m-%d'),
                'location': f'{lang}_Region',
                'followers_count': random.randint(100, 1000000),
                'following': random.randint(50, 5000)
            },
            'content_data': {
                'host_id': f'HID_{random.randint(1000, 9999)}',
                'text_caption': sample_texts[lang] + f' #{lang} #trend',
                'time_stamp': (datetime.now() - timedelta(hours=random.randint(1, 2400))).strftime('%Y-%m-%d %H:%M:%S'),
                'language': lang
            },
            'interaction_data': {
                'likes': random.randint(10, 50000),
                'shares': random.randint(0, 10000),
                'comments': random.randint(0, 5000),
                'hashtags': ['insta', lang.lower(), 'trend']
            },
            'network_relationship': {
                'mutuals': random.randint(0, 100),
                'suggested_followers': random.randint(5, 50),
                'community': f'{lang}_Group',
                'instagram_pages': [f'Page_{random.randint(1,10)}']
            },
            'engagement_matrix': {
                'engagement_rate': round(random.uniform(0.1, 25.0), 2)
            }
        }
        data.append(record)
    return data

# Generate the dataset (5 Lakhs samples as requested)
dataset = generate_osn_data(num_samples=500000)

# Save to JSON
with open('instagram_multi_lang.json', 'w', encoding='utf-8') as f:
    json.dump(dataset, f, ensure_ascii=False, indent=4)
print('Data Extraction simulated and saved to instagram_multi_lang.json')

# Stage 1 Visualization: Data Distribution
df_meta = pd.DataFrame([{'Language': r['content_data']['language'], 'Community': r['network_relationship']['community']} for r in dataset])
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.countplot(data=df_meta, x='Language', ax=axes[0], palette='viridis', order=df_meta['Language'].value_counts().index)
axes[0].set_title('Stage 1: Sample Distribution per Language')
axes[0].tick_params(axis='x', rotation=45)

df_meta['Community'].value_counts().plot.pie(ax=axes[1], autopct='%1.1f%%', cmap='Set3')
axes[1].set_title('Stage 1: Community Network Proportions')
axes[1].set_ylabel('')
plt.tight_layout()
plt.show()

"""## 3. Load Data & Print 5 Samples"""

with open('instagram_multi_lang.json', 'r', encoding='utf-8') as f:
    loaded_data = json.load(f)

print(f"Total loaded samples: {len(loaded_data)}\n")
print("--- First 5 Samples ---")
for idx in range(5):
    print(json.dumps(loaded_data[idx], indent=2, ensure_ascii=False))
    print('-'*50)

"""## 4. Text Preprocessing
Extract captions, remove URLs, mentions, and calculate lengths before and after for stage-wise visualization.
"""

import re

def preprocess_text(text):
    text = re.sub(r'http\S+', '', text) # Remove URLs
    text = re.sub(r'@\w+', '', text) # Remove Mentions
    text = re.sub(r'#\w+', '', text) # Remove Hashtags optionally
    text = re.sub(r'\s+', ' ', text).strip() # Extra spaces
    return text.lower()

original_lengths = []
clean_lengths = []
processed_texts = []
languages_list = []

for record in loaded_data:
    raw = record['content_data']['text_caption']
    clean = preprocess_text(raw)

    original_lengths.append(len(raw))
    clean_lengths.append(len(clean))
    processed_texts.append(clean)
    languages_list.append(record['content_data']['language'])

print("--- Preprocessed First 5 Records ---")
for i in range(5):
    print(f"[{languages_list[i]}] Original: {loaded_data[i]['content_data']['text_caption']}")
    print(f"[{languages_list[i]}] Cleaned : {processed_texts[i]}\n")

# Stage 2 Visualization: Preprocessing Impact
df_lengths = pd.DataFrame({'Original Length': original_lengths, 'Cleaned Length': clean_lengths})
plt.figure(figsize=(10, 5))
sns.kdeplot(df_lengths['Original Length'], fill=True, label='Before Prep')
sns.kdeplot(df_lengths['Cleaned Length'], fill=True, label='After Prep')
plt.title('Stage 2: Text Length Distribution (Before vs After Preprocessing)')
plt.xlabel('Character Count')
plt.legend()
plt.show()

"""## 5. Vectorization Techniques (IndicBERT)
Extracting contextual embeddings without needing a Hugging Face token, natively applying `google/muril-base-cased`.
"""

from transformers import AutoTokenizer, AutoModel
import torch
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# No token required for public models
model_identifier = "google/muril-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_identifier)
model = AutoModel.from_pretrained(model_identifier).to(device)

# Vectorize first 300 samples for reasonable time and scatter plot
sample_texts_subset = processed_texts[:300]
sample_langs_subset = languages_list[:300]

inputs = tokenizer(sample_texts_subset, padding=True, truncation=True, return_tensors="pt", max_length=64).to(device)
with torch.no_grad():
    outputs = model(**inputs)
    # CLS token
    embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()

print("Embeddings shape extracted:", embeddings.shape)

# Stage 3 Visualization: Comparison of PCA and t-SNE Projections
pca = PCA(n_components=2)
components_pca = pca.fit_transform(embeddings)
df_pca = pd.DataFrame({'PCA 1': components_pca[:, 0], 'PCA 2': components_pca[:, 1], 'Language': sample_langs_subset})

tsne = TSNE(n_components=2, random_state=42)
components_tsne = tsne.fit_transform(embeddings)
df_tsne = pd.DataFrame({'t-SNE 1': components_tsne[:, 0], 't-SNE 2': components_tsne[:, 1], 'Language': sample_langs_subset})

fig, axes = plt.subplots(1, 2, figsize=(18, 8))
sns.scatterplot(data=df_pca, x='PCA 1', y='PCA 2', hue='Language', palette='tab10', s=100, alpha=0.7, ax=axes[0])
axes[0].set_title('Stage 3: PCA Projection')
axes[0].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

sns.scatterplot(data=df_tsne, x='t-SNE 1', y='t-SNE 2', hue='Language', palette='tab10', s=100, alpha=0.7, ax=axes[1])
axes[1].set_title('Stage 3: t-SNE Projection')
axes[1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.suptitle('Comparison of PCA and t-SNE Projections of MuRIL Vector Embeddings')
plt.tight_layout()
plt.show()

"""## 6. Evolutionary Metrics & Model Characteristics
Calculating Model Parameters, Size, and assessing BLEU, METEOR, WER, CER values for standard test pairs.
"""

import evaluate
from nltk.translate.meteor_score import meteor_score
from nltk import word_tokenize

# 6.1 Total Parameters and Model Size
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
estimated_size_mb = total_params * 4 / (1024 ** 2)

print("====== MODEL CHARACTERISTICS ======")
print(f"Model Architecture : {model_identifier}")
print(f"Total Parameters   : {total_params:,}")
print(f"Trainable Params   : {trainable_params:,}")
print(f"Size of Model      : ~{estimated_size_mb:.2f} MB\n")

# 6.2 Text Analysis - Evolutionary Metrics
# Defining mock translations/generated text vs references to show evaluation usage.
references = ["this is an amazing post on social media check it out"]
predictions = ["this is a really amazing post on social media check it"]

bleu = evaluate.load("bleu")
wer = evaluate.load("wer")
cer = evaluate.load("cer")

bleu_score = bleu.compute(predictions=predictions, references=references)['bleu']
wer_score  = wer.compute(predictions=predictions, references=references)
cer_score  = cer.compute(predictions=predictions, references=references)

ref_tokens = word_tokenize(references[0])
pred_tokens = word_tokenize(predictions[0])
met_score = meteor_score([ref_tokens], pred_tokens)

print("====== EVOLUTIONARY METRICS ======")
print(f"BLEU Score   : {bleu_score:.4f}")
print(f"METEOR Score : {met_score:.4f}")
print(f"WER          : {wer_score:.4f}")
print(f"CER          : {cer_score:.4f}\n")

# Stage 4 Visualization: Performance Metrics Comparison
metrics_dict = {'BLEU': bleu_score, 'METEOR': met_score, 'WER': wer_score, 'CER': cer_score}
plt.figure(figsize=(8, 5))
sns.barplot(x=list(metrics_dict.keys()), y=list(metrics_dict.values()), palette='coolwarm')
plt.title('Stage 4: Text Analysis Metrics Distribution')
plt.ylabel('Score')
for index, value in enumerate(metrics_dict.values()):
    plt.text(index, value + 0.02, str(round(value, 4)), ha='center')
plt.ylim(0, 1.0)
plt.show()

"""## 7. Advanced Stage-wise Visualizations
We analyze Network Graph topologies (follow connections/communities) and Engagement Matrix.
"""

import networkx as nx
import plotly.express as px

# 7.1 Network Relationship Graph (Sub-sampling for clear graph)
G = nx.Graph()
graph_subset = loaded_data[:40]

for rec in graph_subset:
    user_node = rec['user_profile']['user_name']
    community_node = rec['network_relationship']['community']
    page_node = rec['network_relationship']['instagram_pages'][0]

    G.add_node(user_node, type='user')
    G.add_node(community_node, type='community')
    G.add_node(page_node, type='page')

    # User connects to Community and to Pages (Network Relationships)
    G.add_edge(user_node, community_node)
    G.add_edge(user_node, page_node)

plt.figure(figsize=(14, 10))
pos = nx.spring_layout(G, scale=2, k=0.5)
colors = ['#1f78b4' if G.nodes[n]['type'] == 'user' else '#33a02c' if G.nodes[n]['type'] == 'community' else '#e31a1c' for n in G]
sizes = [100 if G.nodes[n]['type'] == 'user' else 800 for n in G]

nx.draw_networkx_nodes(G, pos, node_color=colors, node_size=sizes, alpha=0.9)
nx.draw_networkx_edges(G, pos, alpha=0.4)
nx.draw_networkx_labels(G, pos, {n: n for n in G if G.nodes[n]['type'] != 'user'}, font_size=10, font_weight='bold')
plt.title('Stage 5: Network Relationship Architecture (Users, Pages, Communities)')
plt.axis('off')
plt.show()

# 7.2 Interactive Engagement Matrix Plot
df_interactive = pd.DataFrame([
    {
        'Language': r['content_data']['language'],
        'Likes': r['interaction_data']['likes'],
        'Comments': r['interaction_data']['comments'],
        'Shares': r['interaction_data']['shares'],
        'Engagement Rate': r['engagement_matrix']['engagement_rate'],
        'Followers': r['user_profile']['followers_count']
    } for r in loaded_data[:1000]
])

fig = px.scatter_3d(df_interactive, x='Likes', y='Comments', z='Shares',
              color='Language', size='Engagement Rate', opacity=0.8,
              title="Stage 6: 3D Engagement Matrix (Likes, Comments, Shares) scaled by Engagement Rate")
fig.update_layout(margin=dict(l=0, r=0, b=0, t=40))
fig.show()

import re
import pandas as pd

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)   # remove links
    text = re.sub(r"@\w+", "", text)      # remove mentions
    text = re.sub(r"#", "", text)         # remove hashtags symbol only
    text = re.sub(r"[\W_]+", " ", text)   # remove punctuation and keep spaces
    return text.strip()

df = pd.DataFrame([{'user_id': record['user_profile']['user_id'], 'caption': record['content_data']['text_caption'], 'likes': record['interaction_data']['likes'], 'comments': record['interaction_data']['comments'], 'shares': record['interaction_data']['shares']} for record in loaded_data])
df['clean_caption'] = df['caption'].apply(clean_text)

from collections import Counter

all_words = " ".join(df['clean_caption']).split()
word_counts = Counter(all_words)

common_words = word_counts.most_common(20)

import matplotlib.pyplot as plt

words, counts = zip(*common_words)

plt.figure()
plt.bar(words, counts)
plt.xticks(rotation=45)
plt.title("Top 20 Most Frequent Words")
plt.show()

from wordcloud import WordCloud

text = " ".join(df['clean_caption'])

wc = WordCloud(width=800, height=400).generate(text)

plt.figure()
plt.imshow(wc)
plt.axis("off")
plt.title("Word Cloud of Captions")
plt.show()

from textblob import TextBlob

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

df['sentiment'] = df['clean_caption'].apply(get_sentiment)

plt.figure()
df['sentiment'].hist()
plt.title("Sentiment Distribution")
plt.show()

users_data = [{'user_id': record['user_profile']['user_id'],
               'user_name': record['user_profile']['user_name'],
               'account_creation': record['user_profile']['account_creation'],
               'location': record['user_profile']['location'],
               'followers_count': record['user_profile']['followers_count'],
               'following': record['user_profile']['following']
              } for record in loaded_data]
users_df = pd.DataFrame(users_data)

merged_df = pd.merge(df, users_df, on="user_id", how="inner")

avg_likes = merged_df.groupby("user_name")["likes"].mean().sort_values(ascending=False).head(10)

plt.figure()
avg_likes.plot(kind='bar')
plt.title("Top Users by Average Likes")
plt.show()

import seaborn as sns

corr = df[['likes', 'comments', 'shares']].corr()

plt.figure()
sns.heatmap(corr, annot=True)
plt.title("Engagement Correlation Heatmap")
plt.show()

sns.pairplot(df[['likes', 'comments', 'shares']])
plt.show()

df['timestamp'] = [record['content_data']['time_stamp'] for record in loaded_data]
df['timestamp'] = pd.to_datetime(df['timestamp'])

time_data = df.groupby(df['timestamp'].dt.date)['likes'].sum()

plt.figure()
time_data.plot()
plt.title("Likes Over Time")
plt.xlabel("Date")
plt.ylabel("Total Likes")
plt.show()

df['language'] = [record['content_data']['language'] for record in loaded_data]
plt.figure()
sns.boxplot(x='language', y='likes', data=df)
plt.xticks(rotation=45)
plt.title("Likes Distribution by Language")
plt.show()

plt.figure()
plt.scatter(components_tsne[:,0], components_tsne[:,1], c=df['likes'].iloc[:300], cmap='viridis')
plt.colorbar()
plt.title("t-SNE Colored by Likes")
plt.show()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

vectorizer = CountVectorizer(max_df=0.9, min_df=10, stop_words='english')
X = vectorizer.fit_transform(df['clean_caption'])

lda = LatentDirichletAllocation(n_components=5)
lda.fit(X)

pip install streamlit pandas matplotlib seaborn wordcloud textblob scikit-learn

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from textblob import TextBlob
from sklearn.manifold import TSNE
import json

# -----------------------------
# LOAD DATA
# -----------------------------
@st.cache_data
def load_data():
    with open('instagram_multi_lang.json', 'r', encoding='utf-8') as f:
        loaded_data = json.load(f)

    posts_data = []
    users_data = []

    for record in loaded_data:
        posts_data.append({
            'user_id': record['user_profile']['user_id'],
            'caption': record['content_data']['text_caption'],
            'likes': record['interaction_data']['likes'],
            'comments': record['interaction_data']['comments'],
            'shares': record['interaction_data']['shares'],
            'timestamp': record['content_data']['time_stamp'],
            'language': record['content_data']['language']
        })
        users_data.append({
            'user_id': record['user_profile']['user_id'],
            'user_name': record['user_profile']['user_name'],
            'account_creation': record['user_profile']['account_creation'],
            'location': record['user_profile']['location'],
            'followers_count': record['user_profile']['followers_count'],
            'following': record['user_profile']['following']
        })

    df = pd.DataFrame(posts_data)
    users_df = pd.DataFrame(users_data)
    return df, users_df

df, users_df = load_data()

# -----------------------------
# TEXT CLEANING
# -----------------------------
import re
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text

df['clean_caption'] = df['caption'].apply(clean_text)

# -----------------------------
# SENTIMENT
# -----------------------------
df['sentiment'] = df['clean_caption'].apply(lambda x: TextBlob(x).sentiment.polarity)

# -----------------------------
# SIDEBAR FILTERS
# -----------------------------
st.sidebar.title("Filters")

selected_language = st.sidebar.multiselect(
    "Select Language",
    options=df['language'].unique(),
    default=df['language'].unique()
)

filtered_df = df[df['language'].isin(selected_language)]

# -----------------------------
# TITLE
# -----------------------------
st.title("📊 Instagram OSN Advanced Dashboard")

# -----------------------------
# KPI METRICS
# -----------------------------
st.subheader("Key Metrics")

col1, col2, col3 = st.columns(3)

col1.metric("Total Posts", len(filtered_df))
col2.metric("Avg Likes", int(filtered_df['likes'].mean()))
col3.metric("Avg Sentiment", round(filtered_df['sentiment'].mean(), 2))

# -----------------------------
# WORD CLOUD
# -----------------------------
st.subheader("Word Cloud")

text = " ".join(filtered_df['clean_caption'])

wc = WordCloud(width=800, height=400).generate(text)

fig, ax = plt.subplots()
ax.imshow(wc)
ax.axis("off")
st.pyplot(fig)

# -----------------------------
# SENTIMENT DISTRIBUTION
# -----------------------------
st.subheader("Sentiment Distribution")

fig, ax = plt.subplots()
filtered_df['sentiment'].hist(ax=ax)
st.pyplot(fig)

# -----------------------------
# HEATMAP
# -----------------------------
st.subheader("Engagement Heatmap")

corr = filtered_df[['likes', 'comments', 'shares']].corr()

fig, ax = plt.subplots()
sns.heatmap(corr, annot=True, ax=ax)
st.pyplot(fig)

# -----------------------------
# TIME SERIES
# -----------------------------
st.subheader("Likes Over Time")

filtered_df['timestamp'] = pd.to_datetime(filtered_df['timestamp'])

time_data = filtered_df.groupby(filtered_df['timestamp'].dt.date)['likes'].sum()

fig, ax = plt.subplots()
time_data.plot(ax=ax)
st.pyplot(fig)

# -----------------------------
# LANGUAGE VS LIKES
# -----------------------------
st.subheader("Likes by Language")

fig, ax = plt.subplots()
sns.boxplot(x='language', y='likes', data=filtered_df, ax=ax)
plt.xticks(rotation=45)
st.pyplot(fig)

# -----------------------------
# t-SNE VISUALIZATION
# -----------------------------
st.subheader("t-SNE Visualization")

sample_df = filtered_df.sample(min(500, len(filtered_df)))

features = sample_df[['likes', 'comments', 'shares']]

tsne = TSNE(n_components=2, random_state=42)
tsne_result = tsne.fit_transform(features)

fig, ax = plt.subplots()
scatter = ax.scatter(tsne_result[:,0], tsne_result[:,1], c=sample_df['likes'])
plt.colorbar(scatter)
st.pyplot(fig)

# -----------------------------
# MULTI-SOURCE MERGE
# -----------------------------
st.subheader("Top Users by Engagement")

if 'user_id' in df.columns and 'user_id' in users_df.columns:
    merged_df = pd.merge(filtered_df, users_df, on="user_id")

    top_users = merged_df.groupby("user_name")["likes"].mean().sort_values(ascending=False).head(10)

    fig, ax = plt.subplots()
    top_users.plot(kind='bar', ax=ax)
    st.pyplot(fig)

# -----------------------------
# RAW DATA VIEW
# -----------------------------
st.subheader("Dataset Preview")
st.dataframe(filtered_df)

import os

# Create a dummy app.py file if it doesn't exist to prevent 'file not found' error on initial run
app_content = """
import streamlit as st
st.set_page_config(layout="wide")
st.title("Instagram OSN Advanced Dashboard")
st.write("The Streamlit app is running. Please refer to the previous cell's output for the actual dashboard code.")
"""
if not os.path.exists('app.py'):
    with open('app.py', 'w') as f:
        f.write(app_content)

get_ipython().system_raw('streamlit run ODFZreGRzrqo.py &')

# Display the public URL provided by ngrok. This is a placeholder. User will need to look at output.
print("Your Streamlit app is running in the background. Check the output above for the public URL.")